// Code generated by qtc from "gen.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line cmd/generator/gen.qtpl:1
package main

//line cmd/generator/gen.qtpl:3
import "strings"

//line cmd/generator/gen.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line cmd/generator/gen.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line cmd/generator/gen.qtpl:6
type Context struct {
	Pkg     string
	Structs []Struct
	Uuid    string
}

//line cmd/generator/gen.qtpl:13
func streamtoLower(qw422016 *qt422016.Writer, str string) {
//line cmd/generator/gen.qtpl:13
	qw422016.N().S(`
`)
//line cmd/generator/gen.qtpl:15
	qw422016.N().S(strings.ToLower(str))
//line cmd/generator/gen.qtpl:16
	qw422016.N().S(`
`)
//line cmd/generator/gen.qtpl:17
}

//line cmd/generator/gen.qtpl:17
func writetoLower(qq422016 qtio422016.Writer, str string) {
//line cmd/generator/gen.qtpl:17
	qw422016 := qt422016.AcquireWriter(qq422016)
//line cmd/generator/gen.qtpl:17
	streamtoLower(qw422016, str)
//line cmd/generator/gen.qtpl:17
	qt422016.ReleaseWriter(qw422016)
//line cmd/generator/gen.qtpl:17
}

//line cmd/generator/gen.qtpl:17
func toLower(str string) string {
//line cmd/generator/gen.qtpl:17
	qb422016 := qt422016.AcquireByteBuffer()
//line cmd/generator/gen.qtpl:17
	writetoLower(qb422016, str)
//line cmd/generator/gen.qtpl:17
	qs422016 := string(qb422016.B)
//line cmd/generator/gen.qtpl:17
	qt422016.ReleaseByteBuffer(qb422016)
//line cmd/generator/gen.qtpl:17
	return qs422016
//line cmd/generator/gen.qtpl:17
}

//line cmd/generator/gen.qtpl:19
func StreamCsvTemplate(qw422016 *qt422016.Writer, ctx Context) {
//line cmd/generator/gen.qtpl:19
	qw422016.N().S(`
package `)
//line cmd/generator/gen.qtpl:20
	qw422016.N().S(ctx.Pkg)
//line cmd/generator/gen.qtpl:20
	qw422016.N().S(`

import (
    "fmt"
    "strconv"
)

`)
//line cmd/generator/gen.qtpl:27
	for _, str := range ctx.Structs {
//line cmd/generator/gen.qtpl:27
		qw422016.N().S(`
func (s *`)
//line cmd/generator/gen.qtpl:28
		qw422016.N().S(str.StructName)
//line cmd/generator/gen.qtpl:28
		qw422016.N().S(`) ParseCSV(rec []string) error {
    index := 0
    `)
//line cmd/generator/gen.qtpl:30
		for i, f := range str.Fields {
//line cmd/generator/gen.qtpl:30
			qw422016.N().S(`
        `)
//line cmd/generator/gen.qtpl:31
			switch f.Type {
//line cmd/generator/gen.qtpl:32
			case "string":
//line cmd/generator/gen.qtpl:32
				qw422016.N().S(`
        s.`)
//line cmd/generator/gen.qtpl:33
				qw422016.N().S(f.Name)
//line cmd/generator/gen.qtpl:33
				qw422016.N().S(` = rec[index]
        `)
//line cmd/generator/gen.qtpl:34
			case "int32":
//line cmd/generator/gen.qtpl:34
				qw422016.N().S(`
        `)
//line cmd/generator/gen.qtpl:35
				qw422016.N().S(strings.ToLower(f.Name))
//line cmd/generator/gen.qtpl:35
				qw422016.N().S(`, err := parse`)
//line cmd/generator/gen.qtpl:35
				qw422016.N().S(ctx.Uuid)
//line cmd/generator/gen.qtpl:35
				qw422016.N().S(`Int32(rec[index])
        if err != nil {
            return fmt.Errorf("error while parsing `)
//line cmd/generator/gen.qtpl:37
				qw422016.N().S(f.Name)
//line cmd/generator/gen.qtpl:37
				qw422016.N().S(` at index: %d", index)
        }
        s.`)
//line cmd/generator/gen.qtpl:39
				qw422016.N().S(f.Name)
//line cmd/generator/gen.qtpl:39
				qw422016.N().S(` = `)
//line cmd/generator/gen.qtpl:39
				qw422016.N().S(strings.ToLower(f.Name))
//line cmd/generator/gen.qtpl:39
				qw422016.N().S(`
        `)
//line cmd/generator/gen.qtpl:40
			case "int64":
//line cmd/generator/gen.qtpl:40
				qw422016.N().S(`
        `)
//line cmd/generator/gen.qtpl:41
				qw422016.N().S(strings.ToLower(f.Name))
//line cmd/generator/gen.qtpl:41
				qw422016.N().S(`, err := parse`)
//line cmd/generator/gen.qtpl:41
				qw422016.N().S(ctx.Uuid)
//line cmd/generator/gen.qtpl:41
				qw422016.N().S(`Int64(rec[index])
        if err != nil {
            return fmt.Errorf("error while parsing `)
//line cmd/generator/gen.qtpl:43
				qw422016.N().S(f.Name)
//line cmd/generator/gen.qtpl:43
				qw422016.N().S(` at index: %d", index)
        }
        s.`)
//line cmd/generator/gen.qtpl:45
				qw422016.N().S(f.Name)
//line cmd/generator/gen.qtpl:45
				qw422016.N().S(` = `)
//line cmd/generator/gen.qtpl:45
				qw422016.N().S(strings.ToLower(f.Name))
//line cmd/generator/gen.qtpl:45
				qw422016.N().S(`
        `)
//line cmd/generator/gen.qtpl:46
			case "float32":
//line cmd/generator/gen.qtpl:46
				qw422016.N().S(`
        `)
//line cmd/generator/gen.qtpl:47
				qw422016.N().S(strings.ToLower(f.Name))
//line cmd/generator/gen.qtpl:47
				qw422016.N().S(`, err := parse`)
//line cmd/generator/gen.qtpl:47
				qw422016.N().S(ctx.Uuid)
//line cmd/generator/gen.qtpl:47
				qw422016.N().S(`Float32(rec[index])
        if err != nil {
            return fmt.Errorf("error while parsing `)
//line cmd/generator/gen.qtpl:49
				qw422016.N().S(f.Name)
//line cmd/generator/gen.qtpl:49
				qw422016.N().S(` at index: %d", index)
        }
        s.`)
//line cmd/generator/gen.qtpl:51
				qw422016.N().S(f.Name)
//line cmd/generator/gen.qtpl:51
				qw422016.N().S(` = `)
//line cmd/generator/gen.qtpl:51
				qw422016.N().S(strings.ToLower(f.Name))
//line cmd/generator/gen.qtpl:51
				qw422016.N().S(`
        `)
//line cmd/generator/gen.qtpl:52
			case "float64":
//line cmd/generator/gen.qtpl:52
				qw422016.N().S(`
        `)
//line cmd/generator/gen.qtpl:53
				qw422016.N().S(strings.ToLower(f.Name))
//line cmd/generator/gen.qtpl:53
				qw422016.N().S(`, err := parse`)
//line cmd/generator/gen.qtpl:53
				qw422016.N().S(ctx.Uuid)
//line cmd/generator/gen.qtpl:53
				qw422016.N().S(`Float64(rec[index])
        if err != nil {
            return fmt.Errorf("error while parsing `)
//line cmd/generator/gen.qtpl:55
				qw422016.N().S(f.Name)
//line cmd/generator/gen.qtpl:55
				qw422016.N().S(` at index: %d", index)
        }
        s.`)
//line cmd/generator/gen.qtpl:57
				qw422016.N().S(f.Name)
//line cmd/generator/gen.qtpl:57
				qw422016.N().S(` = `)
//line cmd/generator/gen.qtpl:57
				qw422016.N().S(strings.ToLower(f.Name))
//line cmd/generator/gen.qtpl:57
				qw422016.N().S(`
        `)
//line cmd/generator/gen.qtpl:58
			}
//line cmd/generator/gen.qtpl:58
			qw422016.N().S(`

        `)
//line cmd/generator/gen.qtpl:60
			if i < len(str.Fields)-1 {
//line cmd/generator/gen.qtpl:60
				qw422016.N().S(`
        index += 1
        `)
//line cmd/generator/gen.qtpl:62
			}
//line cmd/generator/gen.qtpl:62
			qw422016.N().S(`
    `)
//line cmd/generator/gen.qtpl:63
		}
//line cmd/generator/gen.qtpl:63
		qw422016.N().S(`
    return nil
}

`)
//line cmd/generator/gen.qtpl:67
	}
//line cmd/generator/gen.qtpl:67
	qw422016.N().S(`

func parse`)
//line cmd/generator/gen.qtpl:69
	qw422016.N().S(ctx.Uuid)
//line cmd/generator/gen.qtpl:69
	qw422016.N().S(`Int32(s string) (int32, error) {
	if s == "" {
		return 0, nil
	}
	i, err := strconv.ParseInt(s, 0, 32)
	return int32(i), err
}

func parse`)
//line cmd/generator/gen.qtpl:77
	qw422016.N().S(ctx.Uuid)
//line cmd/generator/gen.qtpl:77
	qw422016.N().S(`Int64(s string) (int64, error) {
	if s == "" {
		return 0, nil
	}
	return strconv.ParseInt(s, 0, 64)
}

func parse`)
//line cmd/generator/gen.qtpl:84
	qw422016.N().S(ctx.Uuid)
//line cmd/generator/gen.qtpl:84
	qw422016.N().S(`Float32(s string) (float32, error) {
	if s == "" {
		return 0, nil
	}
	i, err := strconv.ParseFloat(s, 32)
	return float32(i), err
}

func parse`)
//line cmd/generator/gen.qtpl:92
	qw422016.N().S(ctx.Uuid)
//line cmd/generator/gen.qtpl:92
	qw422016.N().S(`Float64(s string) (float64, error) {
	if s == "" {
		return 0, nil
	}
	return strconv.ParseFloat(s, 64)
}
`)
//line cmd/generator/gen.qtpl:98
}

//line cmd/generator/gen.qtpl:98
func WriteCsvTemplate(qq422016 qtio422016.Writer, ctx Context) {
//line cmd/generator/gen.qtpl:98
	qw422016 := qt422016.AcquireWriter(qq422016)
//line cmd/generator/gen.qtpl:98
	StreamCsvTemplate(qw422016, ctx)
//line cmd/generator/gen.qtpl:98
	qt422016.ReleaseWriter(qw422016)
//line cmd/generator/gen.qtpl:98
}

//line cmd/generator/gen.qtpl:98
func CsvTemplate(ctx Context) string {
//line cmd/generator/gen.qtpl:98
	qb422016 := qt422016.AcquireByteBuffer()
//line cmd/generator/gen.qtpl:98
	WriteCsvTemplate(qb422016, ctx)
//line cmd/generator/gen.qtpl:98
	qs422016 := string(qb422016.B)
//line cmd/generator/gen.qtpl:98
	qt422016.ReleaseByteBuffer(qb422016)
//line cmd/generator/gen.qtpl:98
	return qs422016
//line cmd/generator/gen.qtpl:98
}
